### ISSUE TITLE
some resources are not found

### ISSUE THREAD

**Issue by xudaseng** [suessmann/intelligent_traffic_lights#1]
Hello,the resources followings are not found.
WEIGHTS_PATH = '/Users/suess_mann/wd/tcqdrl/tca/saved_model/dqn_1246.pt'

sumoBinary = "/usr/local/opt/sumo/share/sumo/bin/sumo-gui"
sumoCmd = "/Users/suess_mann/wd/tcqdrl/tca/src/cfg/sumo_config.sumocfg"
could you provide them?Thank you.

**Comment by suessmann** [comment]
Hi @xudaseng !

Glad you asked! The thing is, you need to separately install the environment itself (that's for `sumoCmd` and `sumoBinary`), get it from here: [SUMO](https://sumo.dlr.de/docs/Installing.html). `WEIGHTS_PATH` is only used If you have a pre-trained model, you may get it from `/model` directory from the repo, just save it somewhere and insert a path to it.

I should've mentioned this in README tho, thanx for the point.

**Comment by xudaseng** [comment]
Thank you for you answer!

**Comment by kadhi12** [comment]
hi,
what should be the source of sumoTools?
